### ISSUE TITLE
Platform packaging

### ISSUE THREAD

**Issue by vibraphone** [Kitware/SMTK#101]
SMTK should be available for installation using platform-specific distribution channels rather than superbuilds so that developers can easily try it and use it (link to a system SMTK from their custom applications).

Platform | Distribution channel
---------|---------------------
Mac OS X | [Homebrew](http://brew.sh)
Ubuntu | [Launchpad PPA](http://launchpad.net/)
Fedora | ?
Windows | [NuGet](https://www.nuget.org/)

**Comment by BobObara** [comment]
This is a duplicate Issue
