### ISSUE TITLE
Add attribute view options to hide toolbar & set tab direction

### ISSUE THREAD

**Issue by johnkit** [Kitware/SMTK#129]
DataBrowser uses smtk to display some simple editing panels that each consist of a single instanced view.

* Because we don't use advanced levels or categories, I would like to hide the toolbar that appears at the top of the view panel.
* We only use a single instanced view at a time, and would therefore like to hide the tab's graphic itself and/or turn the tab's text into a title on the panel.

There should be project funding available for this, so please see johnT for the deets.

**Comment by BobObara** [comment]
This might be addressed by the new View Mechanism

**Comment by vibraphone** [comment]
I think this is now possible. @johnkit can you verify and close?

**Comment by johnkit** [comment]
Yes, the new View classes fully address this feature request.
