### ISSUE TITLE
Wrong PYTHONPATH for shiboken

### ISSUE THREAD

**Issue by mathstuf** [Kitware/SMTK#132]
Shiboken's `SHIBOKEN_LIBRARY` is `/home/boeckb/misc/root/shiboken/lib/libshiboken-python2.7.so` here while the `PYTHONPATH` is supposed to have `/home/boeckb/misc/root/shiboken/lib64/python2.7/site-packages`. Shiboken should probably set the `PYTHONPATH` necessary for it in its config file, but I'm not sure of the best way to override the logic as-is (or make it continue working for old Shiboken).

**Comment by mathstuf** [comment]
@vibraphone

**Comment by vibraphone** [comment]
@robertmaynard I think you were the one who set up PYTHONPATH for testing and installation as well as the copy+install of shiboken's helper library. I can look at it later this week, but don't know the best practice for Python paths; I know lib/lib64 is an issue on some platforms (Fedora) but don't know the most robust way to detect the platform policy and/or Python install layout (which may not match the platform in a superbuild or drag+drop package).

**Comment by mathstuf** [comment]
Shiboken knows where it installed its file, so I see no reason to not offer that variable at least. Making it match others is a nice-to-have, but really the problem for SMTK is that if we add this to Shiboken, what do we do about older Shiboken versions?

**Comment by mathstuf** [comment]
I guess for the super build, just set it in the cache vie `add_extra_cmake_args` and wire it up properly. Does SMTK care about building outside of the super build *and* without the superbuild?

**Comment by robertmaynard** [comment]
@mathstuf We require a specific fork of Shiboken already, so we can enforce a requirement that people need to upgrade / use the newest version of Shiboken.

**Comment by robertmaynard** [comment]
I would expect that SMTK requires that it can be built and packaged by any superbuild, and isn't tied to a single product.

**Comment by robertmaynard** [comment]
@vibraphone Yes I was the one that initially wrote the copy and install scripts for SMTK. I actually don't remember what my exact solution to the problem is, but I can look into it with @mathstuf.

**Comment by vibraphone** [comment]
@mathstuf wrote:
> Shiboken should probably set the PYTHONPATH necessary for it in its config file, but I'm not sure of the best way to override the logic as-is (or make it continue working for old Shiboken).

I don't care about it working for old Shiboken versions; we already require a special branch for SMTK. If someone patches Shiboken to store the required PYTHONPATH somewhere, I'll update SMTK to use it.

**Comment by mathstuf** [comment]
Fixed by #154.
