### ISSUE TITLE
Failing dashboards

### ISSUE THREAD

**Issue by mathstuf** [Kitware/SMTK#144]
Seems to be due to an SMTK change. See [CDash](https://www.kitware.com/CDash/viewBuildError.php?buildid=549766).

**Comment by mathstuf** [comment]
@vibraphone

**Comment by vibraphone** [comment]
Looks like this was triggered by a change @yumin authored and merged (#134).

**Comment by yumin** [comment]
@mathstuf Is endor up to date with cmb? That smtk change happened a week ago.

**Comment by mathstuf** [comment]
Hmm, the CMB superbuilds have been failing (last success was the 10th, so that's the SMTK CMB is trying to build against now). I'll look into those tomorrow.

**Comment by mathstuf** [comment]
Seeing this with a [fresh build](https://www.kitware.com/CDash/viewBuildError.php?buildid=551641).

**Comment by mathstuf** [comment]
Oops, the last CMB Superbuild might not have installed; let me check.

**Comment by mathstuf** [comment]
Seems to be fine.
