### ISSUE TITLE
Install headers to `smtk-$version` subdirectory

### ISSUE THREAD

**Issue by mathstuf** [Kitware/SMTK#150]
This would fix the "SMTK uses installed headers over its own" problem.

**Comment by vibraphone** [comment]
I would prefer `$INSTALL_PREFIX/include/smtk/$version/` over `$INSTALL_PREFIX/include/smtk-$version/` to avoid polluting the `include` directory with version-numbered subdirs.

**Comment by mathstuf** [comment]
Doesn't matter to me too much. For reference `name-version` is what GNOME-led projects does (they also mangle the SONAME as well, but I wouldn't worry about that too much until/unless you want to preserve ABI compatibility as well).
