### ISSUE TITLE
Update documentation for smtkImplementsModelingKernel

### ISSUE THREAD

**Issue by robertmaynard** [Kitware/SMTK#158]
The documentation for smtkImplementsModelingKernel states it has 5 parameters, but in fact it requires 6, the neweset being the export macro for the session.

**Comment by vibraphone** [comment]
Appears to be fixed in master as of 234efd2 (autoinit: accept an export symbol argument). Do you see something else?

**Comment by robertmaynard** [comment]
The add a bridge tutorial wasnt updated: https://github.com/Kitware/SMTK/blob/master/doc/tutorials/add_a_bridge/session_subclass.rst
