### ISSUE TITLE
Failing dashboards (missing header for discrete's export symbols)

### ISSUE THREAD

**Issue by mathstuf** [Kitware/SMTK#168]
[Failure on CDash](https://www.kitware.com/CDash/viewBuildError.php?buildid=555324).

**Comment by mathstuf** [comment]
@vibraphone

**Comment by vibraphone** [comment]
This will not be the only error if building smtk/master with the superbuild's ParaView.

@mathstuf Does trenzalore build SMTK with ParaView master or the superbuild SHA? If building smtk/master (instead of smtk/release-v1) then PV/master should also be used. See PR #166 .

**Comment by mathstuf** [comment]
OK, the SMTK superbuild runs off of SMTK master. I'll update buildbot to also do ParaView master there.

**Comment by mathstuf** [comment]
Looks like the discrete bridge needs updated for ghost cell changes: https://www.kitware.com/CDash/viewBuildError.php?buildid=555649

**Comment by yumin** [comment]
@mathstuf Are you sure you are using paraview master?

**Comment by mathstuf** [comment]
Oops. I made the branch for buildbot, but hadn't merged it, so it isn't using ParaView's `master`.

**Comment by vibraphone** [comment]
Closing because the original issue has been fixed. The build environment for the buildbot should be a buildbot issue, not an SMTK one.
