### ISSUE TITLE
Enable client-server wrappings for discrete bridge modules

### ISSUE THREAD

**Issue by mathstuf** [Kitware/SMTK#314]
Enabling it is easy, but the client-server wrappers don't work because VTK doesn't set the `_HEADERS` variable properly. This is because SMTK puts its headers in a subdirectory which VTK doesn't really support. I can fix it in VTK, but I really don't know what is going to break because of it. Is there any objection to moving the headers down beside the `module.cmake` file to match the way every other VTK module handles it?

@vibraphone

**Comment by vibraphone** [comment]
No objection from me, but then @yumin is really the one maintaining the discrete bridge. Yumin?

**Comment by yumin** [comment]
Ben decided (and I agreed) to make two modules, one for each subdirectory, and it conceptually makes more sense to make them separate modules.

**Comment by mathstuf** [comment]
I have this mostly working. The problem is that ParaView won't be able to use these client/server wrappings since they're all static and ParaView has already been built.

**Comment by vibraphone** [comment]
By static do you mean the libraries are statically linked? Or do you mean that registration with ParaView happens at PV's compile-time? The first should be easy to fix.

**Comment by mathstuf** [comment]
The `CS` libraries are static.

**Comment by vibraphone** [comment]
Does VTK force it, or are they shared when `BUILD_SHARED_LIBS` is `ON`?

**Comment by mathstuf** [comment]
ParaView forces it.

**Comment by yumin** [comment]
If you link these cs libraries from CMB VTKExtension, can you start
ModelBuilder?

**Comment by mathstuf** [comment]
Finally got to CMB; rebuilding it now.

**Comment by vibraphone** [comment]
Grrr... Short term, I agree that Yumin's idea will (well, should) work. Long term, we need to get PV to install properly and allow branded applications and plugins to build from an install.

**Comment by mathstuf** [comment]
Looks like it should work. Some things need to get fixed though :) .
