### ISSUE TITLE
Handle remote session failure more gracefully.

### ISSUE THREAD

**Issue by vibraphone** [Kitware/SMTK#87]
When a model worker dies, this currently causes the worker's client to hang and/or die. Should we keep a log of RPC requests required to reconstruct a session? How should failures be presented by SMTK to callers?

**Comment by BobObara** [comment]
Shouldn’t we do the same thing we do when a mesh worker die? - in other words the application should see if we lose the “heart beat”

Bob

Robert M. O'Bara, MEng.
Assistant Director of Scientific Computing

Kitware Inc.
28 Corporate Drive
Suite 101
Clifton Park, NY 12065

Phone: (518) 881- 4931

**Comment by vibraphone** [comment]
Currently, I don't think SMTK detects failed workers well. The bug is a reminder to do something about it, not a plan for exactly what should be done.

My concern is what should happen to the model manager... it stores records from potentially multiple sessions. At a minimum, when the worker dies, the records for that session should be removed from the manager. A signal to the application would also be helpful. It would be nice to have a "recover" option that tries to recreate the session up to the last operation. We do not currently record a transaction log, but it would be pretty simple since we already have ways to serialize each operation. The only issue is the serialization may refer to entities by UUIDs that need not be persistent. Recording the results of operations would be enough to reconstruct things but it would take work to reconstruct that way.

**Comment by vibraphone** [comment]
Also, in case the previous reply was unclear, the big difference between the CMBv3 mesh workers and the new SMTK model workers is that the model workers are stateful while the mesh workers were not. If a mesh job failed, the dialog could report failure and allow the user to tweak parameters and resubmit. But if the model worker dies, the operator dialog cannot just resubmit the same operation with a few parameter changes... re-establishing the state prior to the failure would be required.
